// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// PURPOSE: confirms the exact shape of a public mapping's
// auto-generated getter -- it takes the KEY as a parameter and
// returns the VALUE, functioning like a regular function despite
// being compiler-synthesized. Distinct from a public scalar variable's
// zero-argument getter.
contract MappingPublicGetterAutoGenerated {
    mapping(address => uint256) public balances;

    function setup(address account, uint256 amount) public {
        balances[account] = amount;
    }

    // No explicit getter written -- `balances(address)` is auto-generated
    // by the `public` keyword and callable directly as a function.
}